import Link from 'next/link';
import styles from '../../components/customer/customer.module.css';
import Header from '../../components/customer/Header';
export const metadata = { title: 'Help & FAQ | MORROWGO' };
const faq = [
  ['What is a travel eSIM?', 'An eSIM is a digital SIM installed on a compatible phone. A data-only plan provides mobile internet; it does not include a new phone number, standard calls or SMS unless the plan explicitly says otherwise.'],
  ['Does payment confirmation mean my eSIM is ready?', 'No. Payment and eSIM delivery are separate steps. Your order page will say whether the eSIM is awaiting issue, needs review or has been issued. Do not pay again just because installation details have not appeared.'],
  ['My order is awaiting an eSIM. What should I do?', 'Keep your order reference and check the original order page again later. There is no QR code to install until an eSIM has been issued.'],
  ['My order needs a review. Should I place it again?', 'Please do not repeat the purchase. Save your order reference and the message shown on the order page. A review is needed before installation can continue.'],
  ['Can I install the QR code on the demo page?', 'No. The demo page uses sample data. Its QR code contains demonstration text only and cannot install or activate an eSIM.'],
  ['When does my plan start?', 'Activation rules differ by plan. The final plan information must explain whether validity begins on installation or connection to a supported network. Do not assume every plan starts on arrival.'],
  ['Can I keep my usual phone number?', 'On devices that support the required SIM combination, you can keep your usual line alongside a travel eSIM. Check your phone settings and your home carrier’s charges, especially for calls and roaming.'],
  ['What are the refund terms?', 'MORROWGO is still preparing for launch. Plan-specific activation and refund terms will be published before live sales begin. No refund eligibility is promised by this preview.']
];
const sections = [['Getting started',[faq[0]]],['Installation',[faq[4],faq[5]]],['Orders & payments',[faq[1],faq[2],faq[3],faq[7]]],['Using your eSIM',[faq[6]]],['Top ups',[['Can I top up my eSIM?','Compatible top-up packages depend on the issued eSIM. Check My eSIMs for availability. Top-up purchasing is not enabled in this Sandbox preview.']]],['Troubleshooting',[['My eSIM is not connecting. What should I check?','First check whether this is a Sandbox test eSIM: test eSIMs cannot be installed or used. For a live plan, check device compatibility, activation rules and the installation instructions before contacting support.']]]];
export default function Help() { return <div className={styles.page}><Header/><main className={styles.wrap}><span className={styles.label}>SUPPORT</span><h1 className={styles.title}>Travel with clarity.</h1><p className={styles.intro}>Answers about your eSIM,<br/>your order and what comes next.</p>{sections.map(([title,items])=><section key={title} className={styles.faqSection}><h2>{title}</h2><div className={styles.faq}>{items.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section>)}<section id="contact" className={styles.contact}><h2>Still need help?</h2><p>Include your order reference and the status shown. Keep passwords, card details and installation codes private.</p><a className={styles.button} href="mailto:support@morrowgo.com">Contact support →</a></section></main></div>; }
