import Link from 'next/link';
import styles from '../customer.module.css';
export const metadata = { title: 'Help & FAQ | MORROWGO' };
const faq = [
  ['What is a travel eSIM?', 'An eSIM is a digital SIM installed on a compatible phone. A data-only plan provides mobile internet; it does not include a new phone number, standard calls or SMS unless the plan explicitly says otherwise.'],
  ['Does payment confirmation mean my eSIM is ready?', 'No. Payment and eSIM delivery are separate steps. Your order page will say whether the eSIM is awaiting issue, needs review or has been issued. Do not pay again just because installation details have not appeared.'],
  ['My order is awaiting an eSIM. What should I do?', 'Keep your order reference and check the original order page again later. There is no QR code to install until an eSIM has been issued.'],
  ['My order needs a review. Should I place it again?', 'Please do not repeat the purchase. Save your order reference and the message shown on the order page. A review is needed before installation can continue.'],
  ['Can I install the QR code on the demo page?', 'No. The demo page uses sample data. Its QR code contains demonstration text only and cannot install or activate an eSIM.'],
  ['When does my plan start?', 'Activation rules differ by plan. The final plan information must explain whether validity begins on installation or connection to a supported network. Do not assume every plan starts on arrival.'],
  ['Can I keep my usual phone number?', 'On devices that support the required SIM combination, you can keep your usual line alongside a travel eSIM. Check your phone settings and your home carrier’s charges, especially for calls and roaming.'],
  ['What are the refund terms?', 'MORROWGO is still preparing for launch. Plan-specific activation and refund terms will be published before live sales begin. No refund eligibility is promised by this preview.']
];
export default function Help() { return <main className={styles.page}><div className={styles.wrap}><header className={styles.nav}><Link href="/">MORROWGO</Link><div className={styles.links}><Link href="/destinations">Destinations</Link><Link href="/compatibility">Device compatibility</Link></div></header><section className={styles.hero}><span className={styles.eyebrow}>A LITTLE HELP, BEFORE YOU GO</span><h1>Travel with clarity.</h1><p>Answers about your phone, your order and the next step.</p></section><div className={styles.banner}>Pre-launch preview. Real eSIM delivery is not currently enabled.</div><section className={`${styles.card} ${styles.faq}`}><h2>Frequently asked questions</h2>{faq.map(([q,a]) => <details key={q}><summary>{q}</summary><p>{a}</p></details>)}</section><section id="contact" className={styles.card}><h2>Contact & order support</h2><p>Customer support: <a href="mailto:support@morrowgo.com">support@morrowgo.com</a></p><p>General enquiries: <a href="mailto:hello@morrowgo.com">hello@morrowgo.com</a></p><p>For help with an order, include your order reference, checkout time and the status shown. Never send passwords, card details or eSIM installation codes by email.</p><Link href="/demo/order">Explore a sample order →</Link></section><footer className={styles.footer}>MORROWGO · Help before you travel.</footer></div></main>; }
