// Isolated browser integration check: fake Auth/DB only, no emails or live accounts.
// Requires Playwright, a browser, and free ports 3111/3112. See docs/auth-verification.md.
const http=require('http');
const assert=require('node:assert/strict');
const path=require('node:path');
const fs=require('node:fs');
const os=require('node:os');
const repo=path.resolve(__dirname,'..');
const sandbox=fs.mkdtempSync(path.join(os.tmpdir(),'morrowgo-auth-test-'));
for(const item of ['app','components','lib','middleware.js','package.json','public']) fs.cpSync(path.join(repo,item),path.join(sandbox,item),{recursive:true});
fs.symlinkSync(path.join(repo,'node_modules'),path.join(sandbox,'node_modules'),'dir');
process.on('exit',()=>fs.rmSync(sandbox,{recursive:true,force:true}));
process.chdir(sandbox);
Object.assign(process.env,{NODE_ENV:'development',NEXT_PUBLIC_SITE_URL:'http://localhost:3111',NEXT_PUBLIC_SUPABASE_URL:'http://127.0.0.1:3112',NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY:'test-public-key',SUPABASE_SERVICE_ROLE_KEY:'',SUPABASE_SECRET_KEY:''});
const {chromium}=require(process.env.MORROWGO_PLAYWRIGHT_MODULE || 'playwright');
const user={id:'00000000-0000-4000-8000-000000000001',aud:'authenticated',role:'authenticated',email:'browser@example.test',email_confirmed_at:'2026-09-25T00:00:00Z',confirmed_at:'2026-09-25T00:00:00Z',app_metadata:{provider:'email',providers:['email']},user_metadata:{},identities:[],created_at:'2026-09-25T00:00:00Z'};
const counters={signup:0,verify:0,resend:0,recover:0,refresh:0,logout:0,password:0};
let currentPassword='Browser-Test-Password-2026';
const session=()=>{const exp=Math.floor(Date.now()/1000)+3600;const jwt=['eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9',Buffer.from(JSON.stringify({sub:user.id,aud:'authenticated',role:'authenticated',exp,iat:Math.floor(Date.now()/1000)})).toString('base64url'),'testsignature'].join('.');return{access_token:jwt,refresh_token:'test-refresh-token',token_type:'bearer',expires_in:3600,expires_at:exp,user};};
let providersEnabled=true;
const backend=http.createServer(async(req,res)=>{let raw='';for await(const c of req)raw+=c;let body={};try{body=JSON.parse(raw)}catch{}
const u=new URL(req.url,'http://localhost');const json=(data,status=200)=>{res.writeHead(status,{'content-type':'application/json'});res.end(JSON.stringify(data));};
if(u.pathname==='/auth/v1/settings')return json({external:{google:providersEnabled,apple:providersEnabled,email:true}});
if(u.pathname==='/auth/v1/signup'){counters.signup++;return json({...user,email_confirmed_at:null,confirmed_at:null});}
if(u.pathname==='/auth/v1/resend'){counters.resend++;return json({});}
if(u.pathname==='/auth/v1/recover'){counters.recover++;return json({});}
if(u.pathname==='/auth/v1/verify'){counters.verify++;if(body.token_hash?.startsWith('expired'))return json({code:'otp_expired',msg:'private-backend-error'},403);return json(session());}
if(u.pathname==='/auth/v1/token'){if(u.searchParams.get('grant_type')==='password'&&body.password!==currentPassword)return json({code:'invalid_credentials',msg:'private-backend-error'},400);if(u.searchParams.get('grant_type')==='refresh_token')counters.refresh++;return json(session());}
if(u.pathname==='/auth/v1/user'){if(req.method==='PUT'){currentPassword=body.password;counters.password++;}if(!req.headers.authorization?.includes('eyJ'))return json({code:'bad_jwt',msg:'Invalid'},401);return json(user);}
if(u.pathname==='/auth/v1/logout'){counters.logout++;return json({});}
if(u.pathname.startsWith('/rest/v1/'))return json([]);
return json({message:'Not implemented in isolated test'},404);
});
(async()=>{await new Promise(r=>backend.listen(3112,'127.0.0.1',r));const next=require(repo+'/node_modules/next');const app=next({dev:true,dir:sandbox});await app.prepare();const server=http.createServer(app.getRequestHandler());await new Promise(r=>server.listen(3111,r));
const browser=await chromium.launch({executablePath:process.env.MORROWGO_BROWSER_PATH || undefined,headless:true,args:['--enable-unsafe-swiftshader']});const ctx=await browser.newContext({viewport:{width:1440,height:1000}});const page=await ctx.newPage();await page.route('**/api/catalogue/**',route=>route.fulfill({json:{countries:[]}}));let errors=[];page.on('pageerror',e=>errors.push(e.message));const base='http://localhost:3111';const pass=currentPassword;
try {
await page.goto(base+'/account');await page.waitForURL('**/login?next=*');console.log('PASS logged-out account guard');
for(const width of [1440,768,390,375,430]){await page.setViewportSize({width,height:1000});await page.goto(base+'/login');await page.getByRole('button',{name:'Continue with Apple'}).waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await page.locator('input[name=password]').isVisible(),false);assert.equal(await page.locator('p[role=alert]').count(),0);if(width===1440||width===390)await page.screenshot({path:path.join(require('node:os').tmpdir(),`morrowgo-auth-${width}.png`),fullPage:true});await page.getByRole('button',{name:'Continue with Email'}).click();await page.locator('input[name=password]').waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);}console.log('PASS desktop/tablet/mobile widths, initially hidden form, email reveal, no default error');
await page.getByRole('link',{name:'Create an account'}).click();await page.waitForURL('**/register?method=email**');await page.locator('input[name=password]').waitFor();await page.getByRole('link',{name:'Sign in',exact:true}).click();await page.waitForURL('**/login?method=email**');await page.locator('input[name=password]').waitFor();console.log('PASS email method preserved when switching sign in/register');
await page.goto(base+'/register');await page.getByRole('button',{name:'Continue with Email'}).click();await page.getByLabel('Email address',{exact:true}).first().fill(user.email);await page.locator('input[name=password]').fill(pass);await page.getByRole('button',{name:'Create account'}).click();await page.getByText('Check your inbox for a confirmation link.',{exact:false}).waitFor();assert.equal(counters.signup,1);console.log('PASS signup form');
await page.getByText('Resend confirmation email',{exact:true}).click();await page.locator('details input[name=email]').fill(user.email);await page.getByRole('button',{name:'Send confirmation link'}).click();await page.getByText('If your email is waiting for confirmation',{exact:false}).waitFor();assert.equal(counters.resend,1);console.log('PASS resend');
await ctx.clearCookies();await page.goto(base+'/auth/confirm?type=signup&token_hash=valid_signup_test_hash_123456');await page.waitForURL(base+'/account');assert.ok((await ctx.cookies()).some(c=>c.name.startsWith('sb-127-auth-token')));await page.reload();await page.getByRole('button',{name:'Sign out',exact:true}).waitFor();assert.equal((await(await page.request.get(base+'/api/account/session')).json()).authenticated,true);console.log('PASS cross-browser confirmation, SSR cookies, reload/session endpoint');
await page.setViewportSize({width:1440,height:1000});await page.goto(base+'/');await page.getByRole('link',{name:'My account',exact:true}).first().waitFor();console.log('PASS homepage navbar authenticated');
await page.goto(base+'/account');await page.getByRole('button',{name:'Sign out',exact:true}).click();await page.waitForURL(base+'/login');assert.equal((await(await page.request.get(base+'/api/account/session')).json()).authenticated,false);await page.goto(base+'/account');await page.waitForURL('**/login?next=*');console.log('PASS logout/account guard');
await page.getByRole('button',{name:'Continue with Email'}).click();await page.getByLabel('Email address',{exact:true}).first().fill(user.email);await page.locator('input[name=password]').fill('wrong-password');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.getByRole('alert').filter({hasText:'Unable to sign in'}).waitFor();assert.equal((await page.textContent('body')).includes('private-backend-error'),false);await page.locator('input[name=password]').fill(pass);await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForURL(base+'/account');console.log('PASS wrong/correct password');
await page.goto(base+'/forgot-password');await page.getByLabel('Email address').fill(user.email);await page.getByRole('button',{name:'Send reset link'}).click();await page.getByText('If this email has an account',{exact:false}).waitFor();const before=counters.verify;await page.goto(base+'/auth/confirm?type=recovery&token_hash=valid_recovery_hash_123456789');await page.waitForURL('**/reset-password?token_hash=*');assert.equal(counters.verify,before);await page.locator('input[name=password]').fill('New-Browser-Password-2026');await page.getByLabel('Confirm new password',{exact:true}).fill('New-Browser-Password-2026');await page.getByRole('button',{name:'Save new password'}).click();await page.waitForURL('**/login?message=password-updated');assert.equal(counters.password,1);console.log('PASS reset, token consumed only on submission');
await page.goto(base+'/auth/confirm?type=signup&token_hash=expired_signup_hash_123456789');await page.waitForURL('**/login?message=link-invalid');await page.getByRole('alert').filter({hasText:'This link has expired'}).waitFor();console.log('PASS expired link friendly error');
for(const provider of ['Google','Apple']){await ctx.clearCookies();await page.goto(base+'/login');const nav=page.waitForURL('http://127.0.0.1:3112/auth/v1/authorize**');await page.getByRole('button',{name:`Continue with ${provider}`}).click();await nav;const url=new URL(page.url());assert.equal(url.searchParams.get('redirect_to'),base+'/auth/callback');assert.ok(url.searchParams.get('code_challenge'));await page.goto(base+'/auth/callback?code=test-provider-code');await page.waitForURL(base+'/account');await page.reload();console.log(`PASS ${provider} PKCE start/callback/session with isolated provider response`);}
const cookie=(await ctx.cookies()).find(c=>c.name==='sb-127-auth-token');assert.ok(cookie);const saved=JSON.parse(Buffer.from(cookie.value.slice(7),'base64url').toString());saved.expires_at=1;await ctx.addCookies([{...cookie,value:'base64-'+Buffer.from(JSON.stringify(saved)).toString('base64url')}]);await page.reload();assert.ok(counters.refresh>0);console.log('PASS expired session refreshed through SSR middleware');
providersEnabled=false;await page.goto(base+'/login');await page.getByRole('button',{name:'Continue with Google'}).click();await page.getByRole('alert').filter({hasText:'temporarily unavailable'}).waitFor();assert.equal(page.url(),base+'/login');const providerForm=page.getByRole('button',{name:'Continue with Google'}).locator('..');assert.equal(await providerForm.locator('p[role=alert]').count(),1);assert.equal(await page.getByRole('button',{name:'Continue with Apple'}).locator('..').locator('p[role=alert]').count(),0);assert.equal(await providerForm.locator('p[role=alert]').evaluate(el=>getComputedStyle(el).backgroundColor),'rgba(0, 0, 0, 0)');console.log('PASS disabled provider shows small error only beneath the attempted button');
assert.deepEqual(errors,[]);console.log('PASS no browser runtime errors');console.log(JSON.stringify(counters));
}finally{await browser.close();server.close();backend.close();await app.close();}
})().then(()=>process.exit(0)).catch(e=>{console.error(e);process.exit(1)});
