export function orderPresentation(order) {
  if (!order) return { key: 'loading', title: 'Checking your payment', text: 'Please wait while we verify your order.', poll: true };
  if (!order.paid) return { key: 'payment_pending', title: 'Payment confirmation pending', text: 'Your payment has not been confirmed yet. Please do not pay again while we check.', poll: true };
  if (['validation_failed', 'failed', 'fulfillment_failed'].includes(order.status)) return { key: 'attention', title: 'Your order needs a review', text: 'Payment is confirmed, but your eSIM could not be prepared. Keep your order reference. Please do not place the same order again.', poll: false };
  if (order.status === 'ready') return { key: 'ready', title: 'Your eSIM order is ready', text: 'Your eSIM has been issued. Installation delivery is not yet available on this page. Keep your order reference for support.', poll: false };
  if (['validated', 'awaiting_fulfillment'].includes(order.status) || order.fulfillmentStatus === 'awaiting_fulfillment') return { key: 'waiting', title: 'Payment confirmed. Awaiting your eSIM.', text: 'Your order is saved. Your eSIM has not been issued yet, so there is no installation code to use. You do not need to pay again.', poll: false };
  if (order.status === 'fulfilling' && order.fulfillmentStatus === 'transaction_pending') return { key: 'attention', title: 'Your order is being checked', text: 'Payment is confirmed. We are checking the eSIM request before continuing. Please keep your order reference and do not pay again.', poll: false };
  if (['processing', 'fulfilling'].includes(order.status)) return { key: 'processing', title: 'Payment confirmed', text: 'We are checking the next step for your eSIM order. This does not mean the eSIM is ready to install.', poll: true };
  return { key: 'attention', title: 'Your order needs a review', text: 'Payment is confirmed, but we cannot confirm the next step. Keep your order reference and check the help page.', poll: false };
}
