'use client';
import { Text } from './../../components/i18n/Provider';
import en from './../../locales/en.json';
import LanguageSelect from '../../components/i18n/LanguageSelect';
import { useState } from 'react';
import Link from 'next/link';
import {ArrowUpRight} from 'lucide-react';
import Header from '../../components/shared/Header';
import mobile from '../../components/shared/mobile.module.css';
import styles from '../customer.module.css';
export default function Compatibility() {
  const [checks,setChecks] = useState([false,false,false]);
  return <><div className={mobile.only}><Header/></div><main className={`${styles.page} ${mobile.page} ${mobile.compatibility}`}><div className={styles.wrap}><header className={styles.nav}><Link href="/"><Text>{en["m_eef9e6b1a9f1"]}</Text></Link><div className={styles.links}><Link href="/destinations"><Text>{en["m_0fc66bc4363c"]}</Text></Link><Link href="/help"><Text>{en["m_cb01db0194f1"]}</Text></Link><LanguageSelect/></div></header><section className={styles.hero}><span className={styles.eyebrow}><Text>{en["m_bc44d1026b95"]}</Text></span><h1><Text>{en["m_32f97fc59b0c"]}</Text></h1><p><Text>{en["m_001a700f3826"]}</Text></p></section><div className={styles.grid}><section className={styles.card}><h2><Text>{en["m_97f2142cbb71"]}</Text></h2><ol><li><Text>{en["m_76eba17fba59"]}</Text></li><li><Text>{en["m_79d9a9c8c589"]}</Text></li><li><Text>{en["m_d8aafbb625ec"]}</Text></li></ol><a href="https://support.apple.com/en-ie/109316" target="_blank" rel="noreferrer"><Text>{en["m_4e86bf726713"]}</Text><span className={mobile.desktopArrow}>↗</span><ArrowUpRight className={mobile.mobileArrow} size={17} aria-hidden="true"/></a></section><section className={styles.card}><h2><Text>{en["m_1928f95c598b"]}</Text></h2><ol><li><Text>{en["m_c44a6532ec13"]}</Text></li><li><Text>{en["m_b176d2f2d83b"]}</Text></li><li><Text>{en["m_f7d4aacd5ddd"]}</Text></li></ol><a href="https://support.google.com/pixelphone/answer/7086887" target="_blank" rel="noreferrer"><Text>{en["m_69b53973a9a0"]}</Text><span className={mobile.desktopArrow}>↗</span><ArrowUpRight className={mobile.mobileArrow} size={17} aria-hidden="true"/></a></section></div><section className={`${styles.card} ${styles.checklist}`}><h2><Text>{en["m_659f8e3f3405"]}</Text></h2><Text>{[en["m_874fbee42300"],en["m_16c5c3f28fc7"],en["m_feff8a3698c0"]].map((label,i) => <label key={label}><input type="checkbox" checked={checks[i]} onChange={e => setChecks(old => old.map((v,j) => j===i ? e.target.checked : v))} /><Text>{label}</Text></label>)}</Text><p role="status"><Text>{checks.every(Boolean) ? en["m_8a1f953be9a8"] : en["m_002639daa432"]}</Text></p><div className={styles.actions}><Link href="/destinations" className={styles.button}><Text>{en["m_a1d56b4c8342"]}</Text></Link><Link href="/help" className={`${styles.button} ${styles.secondary}`}><Text>{en["m_133b73c757ec"]}</Text></Link></div></section></div></main></>;
}
